# Generated by Django 3.1.3 on 2023-05-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230528_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
